### PR TITLE
sorted and use two spaces as indention

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by WIStudent** [comment]
Are there any specific reasons to use spaces instead of tabs? It increases the file size by almost 9%.

**Comment by rubo77** [comment]
No

**Comment by rubo77** [comment]
But use one space then, which is more failsafe if users add their own

**Comment by rubo77** [comment]
Or even no intentions would save even more

**Comment by rubo77** [comment]
If size matters, i would create it minified without line breaks and space at all.

Maybe a readable source file and an auto generated minified file then

**Comment by WIStudent** [comment]
The first 6 versions of the `ssids.json` file were actually minified. I then added the tabs and line breaks to improve the readability and editability. Before that it was quite hard to tell what was changed when new SSIDs were added.

Adding a minified version isn't as simple as it first sounds. The app still expect the SSIDs to be in the `ssids.json` file, so this file would have to contain the minified version. A new file then would contain the non-minified version. That doesn't sound like a pretty solution either.

Actually I don't think that a minified version is necessary for a file that is smaller than 4 KB. But I also don't see a good argument for replacing the tabs with spaces other than personal perferences. All it currently does is needlessly increasing the file size. So if you don't have a good argument why spaces are superior to tabs I would like to stick with tabs.

**Comment by rubo77** [comment]
Stick with Tabs. That's fine.

But I would recommend to Strip those off also:

Just start each line right at the beginning.

**Comment by rubo77** [comment]
Or you use a git hook that automatically creates the minified version

**Comment by rubo77** [comment]
solved by https://github.com/WIStudent/freifunk-ssids/commit/2092a9e127323b9f148198732198c24447bffccb

**Pull request closed without merging**
